# test against this version of node.js
environment:
  matrix:
  #node.js
  - nodejs_version: "6"

#install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

#post-install test scripts
test_script:
  - node --version
  - npm --version
  - npm test

build: off
